---
  parser: "babel-eslint"
  env:
    es6: true
    browser: true
  extends: "airbnb"
  rules:
    curly:
      - 2
      - "all"
    func-names: 0
    object-curly-spacing:
      - 1
      - "never"
    indent: 0
    object-shorthand: 0
    arrow-body-style:
      - 1
      - "as-needed"
    comma-dangle:
      - 1
      - "always-multiline"
    no-unused-vars: 1
    no-extra-semi: 1
    prefer-const: 1
    max-len:
      - 1
      - 100
      -
        ignoreUrls: true
        ignorePattern: "<.*className|`#\/.*`|import\\W.*"
    space-infix-ops: 1
    space-before-function-paren:
      - 1
      - "never"
    camelcase: 1
    prefer-arrow-callback:
      - 1
    vars-on-top: 1
    eqeqeq: 1
    quotes:
      - 1
      - "single"
    consistent-return: 0
    no-shadow:
      - 1
      -
        builtinGlobals: true
    no-use-before-define:
      - 1
      - "nofunc"
    new-cap:
      - 1
      - capIsNew: false
    semi: 1
    jsx-quotes: 1
    function-paren-newline: 
      - 1
      - consistent
    padded-blocks: 1
    arrow-parens:
      - 1
      - "always"
    quote-props:
      - 1
      - "consistent-as-needed"
    key-spacing: 1
    comma-spacing: 1
    no-underscore-dangle: 0
    no-param-reassign:
      - "error"
      - {"props": false}
    object-curly-newline:
      - 1
      - ObjectExpression:
          multiline: true
          consistent: true
    no-multi-spaces: 1
    no-mixed-operators: off
    no-debugger: 1
    space-in-parens: 1
    class-methods-use-this: 1
    no-restricted-syntax: 0
    no-restricted-properties: 1
    no-plusplus: 0
    no-continue: 1
    no-loop-func: 0
    no-console:
    - warn
    - allow:
      - info
      - warn
      - error
    prefer-destructuring: 0
    block-spacing:
      - 1
      - "never"
    spaced-comment: 1
    import/extensions: 0
    import/first: 0
    import/no-unresolved:
      - error
      - ignore:
          - -REACT_APP_PROJECT_NAME
    import/prefer-default-export: 0
    import/newline-after-import:
      - warn
      - count: 2
    import/order:
      - warn
      - newlines-between: always-and-inside-groups
    import-order-autofix/order:
      - warn
      - newlines-between: always
    react/forbid-prop-types: 0
    react/require-default-props: 1
    react/jsx-curly-brace-presence: 1
    react/prop-types: 1
    react/jsx-first-prop-new-line: 0
    react/jsx-filename-extension:
      - 1
      - extensions:
        - ".js"
        - ".jsx"
    react/jsx-indent: 0
    react/jsx-indent-props: 0
    react/jsx-boolean-value:
      - 1
      - "always"
    react/prefer-stateless-function: 1
    react/no-multi-comp: 0
    react/jsx-tag-spacing:
      - error
      - beforeSelfClosing: "always"
    react/no-unused-state: 1
    react/no-array-index-key: 1
    react/sort-comp: 1
    react/no-unused-prop-types: 1
    jsx-a11y/alt-text: 1
    jsx-a11y/click-events-have-key-events: 1
    jsx-a11y/no-static-element-interactions: 0
    jsx-a11y/label-has-for:
      - 0
      -
        components: [ "Label" ]
        required:
          every: [ "id" ]
        allowChildren: false
  plugins:
    - react
    - import
    - import-order-autofix
